# cluster_config.yml - cluster configuration
__default__:
    account: jjberg
    partition: broadwl
    time: 36:00:00 # time limit for each job
    nodes: 1
    ntasks-per-node: 14
    chdir: largeEffectInsensitivity/ #
    output: largeEffectInsensitivity-%j.out
    error: largeEffectInsensitivity-%j.err
